import assert from "node:assert/strict";
import test from "node:test";
import { assessMessageRisk, detectCommitments, findIntroductionPaths, mergeContacts, nextBestAction, optimizeSequence, parsePeopleQuery, relationshipDecay, searchPeople, type ContactProfile } from "./intelligence";
import { decryptPrivateContext, encryptPrivateContext, minimizeForAI, redactSensitiveText } from "./privacy";

const now = new Date("2026-08-07T12:00:00Z");
const contact = (overrides: Partial<ContactProfile> = {}): ContactProfile => ({ id:"maya", name:"Maya Chen", emails:["maya@northstar.ai"], company:"Northstar AI", companyDomain:"northstar.ai", role:"Founder", topics:["AI","developer tools"], lastInteractionAt:new Date("2026-08-01T12:00:00Z"), sentCount:20, receivedCount:19, threadCount:8, replyRate:.85, strengthScore:82, ...overrides });

test("detects relationship decay relative to the relationship cadence",()=>{const result=relationshipDecay(contact({lastInteractionAt:new Date("2025-11-01T12:00:00Z"),strengthScore:42,previousStrengthScore:80}),now);assert.equal(result.state,"critical");assert.ok(result.risk>=75)});
test("parses natural-language people search and ranks matches",()=>{const plan=parsePeopleQuery("Founders I spoke with last quarter who work in AI",now);assert.deepEqual(plan.filters.roles,["founder"]);assert.ok(plan.filters.after);const result=searchPeople("founders who work in AI",[contact(),contact({id:"dev",name:"Dev",role:"Engineer",topics:["payments"]})],now);assert.equal(result[0].contact.id,"maya")});
test("merges aliases only with strong identity evidence",()=>{const merged=mergeContacts([contact(),contact({id:"m2",emails:["maya.chen@gmail.com"],sentCount:2,receivedCount:1})],[{leftEmail:"maya@northstar.ai",rightEmail:"maya.chen@gmail.com",kind:"provider-id",confidence:1}]);assert.equal(merged.length,1);assert.equal(merged[0].emails.length,2)});
test("finds the strongest bounded introduction path",()=>{const contacts=[contact(),contact({id:"target",name:"Tara",company:"Acme",emails:["tara@acme.com"]})];const paths=findIntroductionPaths("me","Acme",contacts,[{from:"me",to:"maya",strength:90,sharedThreads:4,lastSeenAt:now},{from:"maya",to:"target",strength:74,sharedThreads:2,lastSeenAt:now}]);assert.deepEqual(paths[0].path,["me","maya","target"])});
test("extracts commitments and overdue state",()=>{const output=detectCommitments([{id:"1",threadId:"t",from:"me",to:["maya"],subject:"Follow-up",body:"I'll send the proposal tomorrow.",occurredAt:new Date("2026-08-01T12:00:00Z"),direction:"sent"}],now);assert.equal(output[0].owner,"me");assert.equal(output[0].status,"overdue");assert.equal(nextBestAction(contact(),output,now).action,"fulfill_commitment")});
test("blocks sensitive data and aggressive language",()=>{const result=assessMessageRisk("Final warning: my API key: abc123. You must reply immediately.");assert.equal(result.level,"block");assert.equal(result.canAutoSend,false);assert.ok(result.flags.length>=2)});
test("optimizes sequence timing from observed replies",()=>{const result=optimizeSequence({replyHours:[9,9,10,9,15],timezone:"Asia/Kolkata",stepReplyRates:[.3,.02],currentDelaysHours:[48,72]});assert.equal(result.preferredHour,9);assert.ok(result.optimizedDelaysHours[1]>72)});
test("redacts and minimizes model context",()=>{assert.equal(redactSensitiveText("Email a@b.com, password: hello"),"Email [EMAIL], [SECRET]");assert.equal(minimizeForAI({subject:"Hi",body:"safe",participants:[]}).allowed,false)});
test("encrypts private relationship context with authenticated encryption",()=>{const secret="a-very-long-tenant-specific-secret";const encrypted=encryptPrivateContext({summary:"private"},secret);assert.notEqual(encrypted.includes("private"),true);assert.deepEqual(decryptPrivateContext(encrypted,secret),{summary:"private"})});
